import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Container, Flex, HStack, Text } from '@chakra-ui/react'
import { MenuItem } from 'components/molecules/MenuItem/MenuItem'
import { Hero } from 'components/molecules/Hero/Hero'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home () {
  return (
    <>
      <Head>
        <title>COG Automation System</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Flex w='100%' p={4} alignContent='center' flexDirection='row'>
        <Image
          src='/images/cog-logo.png'
          width={35}
          height={30}
          alt='Logo Image'
        />
        <Text
          fontSize='22px'
          lineHeight='42px'
          flexGrow={1}
          marginLeft='10px'
          fontWeight='700'
          color='#2085CE'
        >
          COG Daraga
        </Text>

        <HStack spacing='16px' alignContent='center'>
          <MenuItem>
            <Link href='/about'>About</Link>
          </MenuItem>
          <MenuItem>
            <Link href='/c2s'>C2S</Link>
          </MenuItem>
          <MenuItem>
            <Link href='/contact'>Contact</Link>
          </MenuItem>
        </HStack>
        <Flex marginLeft='40px'>
          <Button variant='solid' colorScheme='blue'>
            Dashboard
          </Button>
        </Flex>
      </Flex>
      <Hero></Hero>
    </>
  )
}
